services:
  
  pm-backend:
    image: rimvanvliet/pm-backend:${PM_DEV_VERSION}
    container_name: pm-backend
    environment:
      - TZ=Europe/Amsterdam
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "3040:3040"
      - "8888:8888"
    depends_on:
      - pm-database
    restart: always

  pm-database:
    image: rimvanvliet/pm-database:${PM_DEV_VERSION}
    container_name: pm-database
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=pm
      - POSTGRES_PASSWORD=pm
      - POSTGRES_DB=pm
    volumes:
      - pm-database:/bitnami/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pm-database:
