services:

  pm-frontend:
    image: rimvanvliet/pm-frontend:${PM_DEV_VERSION}
    container_name: pm-frontend
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "3030:3030"
    networks:
      - npm_default
    depends_on:
      - pm-backend
    restart: always

  pm-backend:
    image: rimvanvliet/pm-backend:${PM_DEV_VERSION}
    container_name: pm-backend
    environment:
      - TZ=Europe/Amsterdam
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - npm_default
    ports:
      - "3040:3040"
      - "8889:8888"
    depends_on:
      - pm-database
    restart: always

  pm-database:
    image: rimvanvliet/pm-database:${PM_DEV_VERSION}
    container_name: pm-database
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=pm
      - POSTGRES_PASSWORD=pm
      - POSTGRES_DB=pm
    volumes:
      - pm-database:/bitnami/postgresql/data
    networks:
      - npm_default
    ports:
      - "5434:5432"
    restart: always

volumes:
  pm-database:

networks:
   npm_default:
    external: true